version: "2"
services:

  smsapi:
    image: krzysbaranski/smsapi2email
    build: .
    ports:
      - 8080:8080
    environment:
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - PORT=8080
      - DOMAIN=example.com

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
