version: "2"
services:
  smsapi:
    build: .
    ports:
      - 8080:8080
    environment:
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - DOMAIN=example.com
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
